site_name: svalidate
#repo_url: https://github.com/timo-schmid/svalidate
#repo_name: GitHub
pages:
- Introduction: 'index.md'
- Basic Usage: 'usage.md'
- Custom Validators: 'custom.md'
- Complex Validators: 'multi.md'
theme: readthedocs

