site_name: svalidate
pages:
- Introduction:       01-INTRO.md
- Basic Usage:        02-BASIC-USAGE.md
- Introduction:       03-CUSTOM-VALIDATORS.md
- Complex Validators: 04-MULTI-VALUE-VALIDATORS.md
theme: readthedocs
